# Generated by Django 5.1.4 on 2025-01-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_razorpay_order_id_cart_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_signature',
        ),
    ]
